---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
stringData:
  # if monValueFromSecret is set to "monitors", uncomment the
  # following and set the mon there
  #monitors: BASE64-ENCODED-Comma-Delimited-Mons
  userID: admin
  userKey: AQDtdBtd1vNRIxAAsUbIzVG7knUlRrKMs0d8Pg==
